version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    # environment:
    #   MYSQL_USER: 'user'
    #   MYSQL_PASSWORD: 'mysql'
    #   MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"  
  mongo4:
    image: mongo:4.4
    restart: always
    ports:
      - '27017:27017'
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
# Names our volume
volumes:
  my-db: